apiVersion: apps/v1
kind: Deployment
metadata:
  name: excel-batch-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excel-batch-processor
  template:
    metadata:
      labels:
        app: excel-batch-processor
    spec:
      containers:
        - name: excel-batch-processor
          image: andersonelit/excel-batch-processor:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: excel-batch-processor-service
spec:
  selector:
    app: excel-batch-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: excel-batch-processor-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: excelbatchprocessor.andersonelit.com
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: excel-batch-processor-service
                port:
                  number: 80